### ISSUE TITLE
what does the FAKE_SYSTEM_LIBS for ?

### ISSUE THREAD

**Issue by pzz2011** [abhinavvishnu/matex#4]
I want to know why do u use FAKE_SYSTEM_LIBS/xxxxx.so 
can you give me some hint? thanks

**Comment by cabe1980** [comment]
Good morning,

The FAKE_SYSTEM_LIBS is an internal environment variable that is set by the setAlias scripts to support Linux kernels before 3.0. It points to a local system library folder that will allow TF to run on older kernels with the provided wheels.

Please let us know if you have any problems or issues. If you have a newer kernel (if you can run TF 1.0 w/o any problems) you will not need to set this variable and the testing scripts can be changed to just calling the python program directly  instead of the entire ld line: $FAKE_SYSTEM_LIBS/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 --library-path $PNETCDF_INSTALL_DIR/lib:$FAKE_SYSTEM_LIBS/lib/:$FAKE_SYSTEM_LIBS/lib/x86_64-linux-gnu/:$FAKE_SYSTEM_LIBS/usr/lib64/gconv:$FAKE_SYSTEM_LIBS/usr/lib64/audit:$FAKE_SYSTEM_LIBS/usr/lib64:$LD_LIBRARY_PATH $TF_INSTALL_DIR/py_distro/bin/python3.4.

Please contact us with any questions

Regards

Joseph
